### ISSUE TITLE
Change notification toolbar & feedback modal into a page-action & pop-up

### ISSUE THREAD

**Issue by johngruen** [mozilla/blok#103]
Per Aislinn's mockups...what is the feasibility of doing something like this?

https://www.dropbox.com/s/a047wk11wknyw68/doorhanger2.png?dl=0
![xyn-ohv0te93eeibofnkd0pbxvseukanpdg4ab11tz8](https://cloud.githubusercontent.com/assets/3323249/17572628/84089398-5f23-11e6-873e-db7abcb46dde.png)

**Comment by groovecoder** [comment]
Okay, this looks very do-able so far ... 

![blok-pageaction](https://cloud.githubusercontent.com/assets/71928/17593950/359695cc-5fad-11e6-85a4-667a84ec43d1.png)

Need to:

* [ ] Investigate if page action popup can re-use the same browser messaging as the content script
* [ ] Update the page action popup UI

Give me another hour or so and I should know how long the whole thing will take.

**Comment by groovecoder** [comment]
Can't re-use the runtime messaging because the page action pop-up isn't constant running like the content script was. Need to think about state management between these components. But I'm pretty sure it will be possible ... just needs some research.

**Comment by groovecoder** [comment]
I pushed up a checkpoint commit where I have the page action displaying correctly using a (horrible) window.* variable for the enabled/disabled state. Next up will be to change the toolbar.html UI into popup.html UI.

So a page action is looking likely, but that’s the last major change I feel comfortable making to make sure we can release by (early) Sep

But I very much want to look at using redux or something better for managing all the state that’s being used by the different components of the add-on now.

I think page action + popup UI + redux + telemetry + continuous delivery pipeline is all do-able in the next 2-3 weeks

**Comment by groovecoder** [comment]
@johngruen - the copy here is very different from the toolbar. Is that on purpose? Or should I re-use as much of the toolbar+feedback copy as possible in this new form-factor?
