### ISSUE TITLE
Disabling the Blok experiment while on a blocked page, breaks the page bottom UI

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/blok#106]
[Affected versions]:
- Nightly 50.0a1
- Test Pilot 0.8.5 -dev-c071788

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Test Pilot add-on is installed on a clean profile.
- Blok experiment is enabled on the used profile.

[Steps to reproduce]:
1. Open the browser and navigate to a page that tracks user's action (eg http://goo.gl/CY4AUu).
2. After the blok bar is displayed on the website disable the blok experiment from "about:addons" or Test Pilot.
3. Return to the tab with the tracking website and observe the bottom of the page.

[Expected result]:
- The bottom of the page is correctly displayed.

[Actual result]:
- At the bottom of page, artifacts of blok bar and its buttons dialogs are wrongly displayed.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/NqGG5F.

**Comment by groovecoder** [comment]
Thanks for the bug report. I'm doing a big change to the UI implementation now. I'll keep this in mind as I do it, and may close this out as soon as that's done.

**Comment by groovecoder** [comment]
This has moved to a page action popup UI, and is being tracked in #115 and should be fixed in #126.
