### ISSUE TITLE
The third-party checks should match the ones done in platform

### ISSUE THREAD

**Issue by fmarier** [mozilla/blok#11]
* [x] #1: Only block 3rd-party requests if the request domain isn't in the same "group" as the origin domain
  * https://github.com/mozilla/blok/pull/23
* [x] #16: Do not block iframe requests to one of its ancestors' top-level domains
  * https://github.com/mozilla/blok/pull/18

**Comment by groovecoder** [comment]
@fmarier - To organize this work for myself, I broke this issue up into 3 sub-issues. Can you check them and make sure I'm still accurate on the scope of the work that needs to be done for this?

**Comment by groovecoder** [comment]
These are all fixed. @fmarier I'm going to meet with @rbillings to discuss QA for Blok. Is there a QA doc/list/plan for platform tracking protection that covers all of these cases? If not, I'll work with her to create one and we'll send it to you for review.

**Comment by fmarier** [comment]
> Is there a QA doc/list/plan for platform tracking protection that covers all of these cases? If not, I'll work with her to create one and we'll send it to you for review.

There isn't one, but that would be handy to have.

I would suggest working with @mwobensmith instead though since this has to do with QAing the client, not the server.
