### ISSUE TITLE
Make Blok compatible with e10s

### ISSUE THREAD

**Issue by clouserw** [mozilla/blok#114]
Let's make sure Blok works with e10s.  I think we need to add 'multiprocess: true' to the permissions list in the manifest.  Some links about compatibility are at https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/

**Comment by groovecoder** [comment]
@rbillings and I have both tested in Dev & Nightly editions which are default e10s-enabled. I just re-tested latest Blok in Dev edition and it's working as expected. So, we're good with e10s.

**Comment by madig** [comment]
Enabling this extension and Test Pilot disables multiprocess windows on 50 according to `about:support`, because of addons...

**Comment by groovecoder** [comment]
Hmm ... I'll check when I get to a Windows machine later today.
