### ISSUE TITLE
Changes made in Blok panel for a website are applied for all websites in the active tabs

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/blok#115]
[Affected versions]:
- Nightly 51.0a1
- Blok v0.1.12

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Blok add-on (v0.1.12) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to multiple websites that you know they track user actions, each in a different tab (e.g. theguardian.com, cnn.com, etc).
2. Choose one of the opened tabs and click on the Blok icon in the address bar.
3. When the Blok panel shows up, click on the toggle button for "Blok is enabled for this site."
4. Click on the Blok icon and observe that the panel text has changed.
5. Switch to another tab, click on the Blok icon and observe the panel text.

[Expected result]:
- The default Blok option is displayed for each tab that hasn't been modified.

[Actual result]:
- If the Blok option is disabled for one of the websites, the change is applied to all websites in the active tabs.

[Notes]:
- Same issue applies for all changes in Blok panel ("Problem reporting" or "This page works")
- If the Blok panel is open and you navigate on different tabs using the short key combination CTRL+TAB, you can observe that the Blok panel remains displayed for all tabs.
- If a new webstite that traks user actions is opened in a new tab, the Blok option would not be affected by the previously opened websites.
- Added a screen recording with the issue: 	
https://goo.gl/mUWGwn

**Comment by groovecoder** [comment]
Thanks. I got back to this and notice the same behavior in the latest 0.1.13 release. I'm starting a branch that will use React to render the UI more consistently based on a state object. Better state structure and consistent rendering should help bugs like this and https://github.com/mozilla/blok/issues/116.

But if I can't get React working by today, I'll fix this and https://github.com/mozilla/blok/issues/116 with more thorough rendering code in the current architecture.

**Comment by SoftVision-EmilPasca** [comment]
I have retested this issue on Windows 10 x64 with the Firefox (48.0.2) and the latest Nightly (51.0a1-20160905030222) using the latest Blok (v0.1.13) and the issue is no longer reproducible.
