### ISSUE TITLE
Both "Blok is enabled and disabled" messages are displayed in private window

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/blok#116]
[Affected versions]:
- Nightly 51.0a1
- Blok v0.1.12

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Blok add-on (v0.1.12) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and open a new private window.
2. Navigate to a website that tracks user actions (e.g. theguardian.com, cnn.com, etc).
3. Click on the Blok icon in the address bar.
4. Observe the text next to the toggle button at the bottom of the Blok Panel.

[Expected result]:
- "Blok is disabled for this site." single message is displayed.

[Actual result]:
- Both "Blok is enabled for this site." and "Blok is disabled for this site." messages are displayed.

[Notes]:
- The toggle button should be disabled in private window since Blok should not work on it. Currently you can click it and the Blok doorhanger closes.
- Added a screenshot with the issue:
![blokisdisabledforthissite_issue](https://cloud.githubusercontent.com/assets/20083658/17854012/8bcbe748-6878-11e6-86b5-956ba4f2ae07.jpg)

**Comment by groovecoder** [comment]
The double/conflicting label is a bug.

I don't think we've decided that Blok should be disabled in private browsing windows. @johngruen ?

**Comment by ashgrigas** [comment]
I think it should otherwise users would have to manage two controls to disable tracking for a specific site and that would be confusing...

Aislinn Dewey Grigas
UX Design Consultant
www.aislinndewey.com

---> sent from my spellcheckless iPhone at 978.930.3729

**Comment by SoftVision-EmilPasca** [comment]
I have retested this issue on Windows 10 x64 with the Firefox (48.0.2) and the latest Nightly (51.0a1-20160905030222) using the latest Blok (v0.1.13) and the issue is no longer reproducible.
