### ISSUE TITLE
Create Privacy Notice for Tracking Protection

### ISSUE THREAD

**Issue by ckprice** [mozilla/blok#117]
/edit changing this a bit to focus on generating the PN. Looks like there's already a `metrics.md` file.

Each experiment has a brief ~3-4 bullet point privacy notice. Example: see left-hand column "Your privacy" [here](http://testpilot.dev.mozaws.net/experiments/activity-stream).

These are built based on a `metrics.md` file that details (among other things) data the add-on collects.

**Comment by ckprice** [comment]
@groovecoder please confirm that https://github.com/mozilla/blok/blob/master/docs/metrics.md is up to date as far as what will be ready for launch.

**Comment by groovecoder** [comment]
Yup I just fixed this by merging https://github.com/mozilla/blok/pull/94.

**Comment by groovecoder** [comment]
Uplift from email: https://docs.google.com/document/d/1u6P5JtvymBu5RMvu6WdKnEVCpm-Yfgv18pTrjDEmtTI/edit?ts=57bb6e5f

**Comment by ckprice** [comment]
This is final, and Trello board is updated.
