### ISSUE TITLE
Switch from Radio to Checkboxes on feedback page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#121]
In today's edition of "Peter complains about everything"...

If I'm reporting a potential issue w/ Blok, should I be able to select multiple potential issues (ie: "Images" _and_ "Video")? Or just one problem?

Not sure how many potential downstream problems this may have w/ database schemas and telemetry pings, so quite possibly not worth the effort in allowing me to report multiple breakages via the form.

![menubar_and_firefox_test_pilot_-_blok](https://cloud.githubusercontent.com/assets/557895/17903144/3d85de02-691f-11e6-8505-cc85bacb0577.png)

**Comment by groovecoder** [comment]
Good point. @johngruen @ashgrigas : what do you think about changing the breakage options from radio/exclusive to checkbox/multiple ?

**Comment by ashgrigas** [comment]
I'm fine with that.

Aislinn Dewey Grigas
UX Design Consultant
www.aislinndewey.com

---> sent from my spellcheckless iPhone at 978.930.3729

**Comment by johngruen** [comment]
I'm thinking there's an 'if it ain't broke' arguement here. Closing since the current implementation seems to be providing the data we need.
