### ISSUE TITLE
Able to resize TextArea when giving feedback

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#122]
Not a huge deal, but means I can do silly stuff like this:

![firefox_test_pilot_-_blok](https://cloud.githubusercontent.com/assets/557895/17903415/426cd87a-6920-11e6-94d7-12f68850b87c.png)

Or annoying stuff like this, where I lose my submit button and cannot scroll down to see it:

<img width="422" alt="firefox_test_pilot_-_blok" src="https://cloud.githubusercontent.com/assets/557895/17903449/5da3e5de-6920-11e6-870e-6e44f14d5142.png">

Potentially relevant: https://davidwalsh.name/textarea-resize

**Comment by hoosteeno** [comment]
@pdehaan, do you think the solution to this issue is to prevent the textarea from being resized? If so, 
I believe this issue was fixed with https://github.com/mozilla/blok/commit/d4a08c36bb9ef8b1a9ff50cba2db3e2431f89505#diff-ee3ee1f5e41b17add6fb32c8c6578e23R128. Suggest WORKSFORME.

**Comment by pdehaan** [comment]
Ah yes... Unable to repro in 1.0rc7. Closing as ¯\\\_(ツ)\_/¯ 

Thanks @hoosteeno
