### ISSUE TITLE
Blok still blocks (some) trackers when set to disabled

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blok#132]
STR:

0. Open Network dev tool and Browser Console to view tracker requests and Blok logging statements, respectively
1. Go to reddit.com with Blok enabled
  * Should see "blocked N requests: ..." in Browser Console; none of the blocked domains should appear in the Network dev tool
2. Disable Blok
  * (It should automatically reload reddit.com)

Expected results:
The Browser Console output should show "allowed N requests: ...", and the blocked domains should appear in the Network dev tool

Actual results:
The Browser Console still shows "blocked N requests: ...", and the blocked domains don't appear in the Network dev tool

**Comment by groovecoder** [comment]
Blok only allows requests that come directly from the disabled origin. E.g.,

economist.com -> securepubads.g.doubleclick.net (allowed)

When trackers request other trackers, Blok **still blocks** the secondary requests. E.g.,

economist.com -> securepubads.g.doubleclick.net (allowed) -> cm.g.doubleclick.net (blocked)

@fmarier, @ashgrigas: To match existing Tracking Protection, I assume we should allow all secondary (tertiary, etc.) tracking requests when a user disables Blok for a site?

**Comment by fmarier** [comment]
> To match existing Tracking Protection, I assume we should allow all secondary (tertiary, etc.) tracking requests when a user disables Blok for a site?

Yes, that's what TP does. If you whitelist a page, we don't run TP on it or its iframes.

**Comment by ashgrigas** [comment]
yes match what TP does
