### ISSUE TITLE
Submit error style nits

### ISSUE THREAD

**Issue by johngruen** [mozilla/blok#133]
## Currently
<img width="407" alt="screen shot 2016-09-06 at 6 50 05 pm" src="https://cloud.githubusercontent.com/assets/3323249/18282775/e6c9c5ac-7462-11e6-9a98-a7790b9da56f.png">

## Expected
Error string should be before the form label and there should be a line break between the two

**Comment by groovecoder** [comment]
Partial dupe of https://github.com/mozilla/blok/issues/123 which is fixed, but not released in a new version/XPI yet.

The non-duplicate part is moving the error string before form label, which I'll fix.

**Comment by johngruen** [comment]
high five

**Comment by johngruen** [comment]
@groovecoder i don't really think we need this w/ the style PR

**Comment by groovecoder** [comment]
![problem-fix-itself](https://cloud.githubusercontent.com/assets/71928/18353706/b7e8ef3c-75a8-11e6-827a-f669210a8cf8.gif)
