### ISSUE TITLE
blockedRequests[requestTabID] is undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#149]
I think this is the same issue as #52, but I'm still seeing it in v1.0rc3:

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18494351/756f7efc-79ca-11e6-8006-1d8e8a8021d3.png)

![browser_console](https://cloud.githubusercontent.com/assets/557895/18494367/9353d332-79ca-11e6-8ce7-e21501d27789.png)

**Comment by groovecoder** [comment]
Will check this out ASAP ... but my browser toolbox console has stopped showing all my log messages for some reason. 😢 Might take a bit ...

**Comment by groovecoder** [comment]
This seems to happen when windows are opened. It doesn't break anything ... mostly just annoying.
