### ISSUE TITLE
Unable to disable Tracking Protection for a page via toggle

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#150]
I'm using Tracking Protection 1.0rc7 on FF Nightly 51, and it looks like I cannot disable the tracking protection using the toggle button in the doorhanger.

Nothing interesting coming up in the Browser Console that looks related.

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/18525274/9b53bc2c-7a70-11e6-93fb-f5b47530822f.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18525392/1fab9418-7a71-11e6-885b-2fc9dc92aeea.png)

![firefox_test_pilot_-_blok_and_new_issue_ _mozilla_blok](https://cloud.githubusercontent.com/assets/557895/18525376/0f89bb14-7a71-11e6-8720-f32bfbdfc39a.png)

**Comment by pdehaan** [comment]
Weird, after updating Firefox Nightly to today's build, I'm unable to repro.
Maybe something weird w/ staged updates, or just an intermittent thing.

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/18525537/bca9dad6-7a71-11e6-94f5-f36138e98bae.png)

![fix__147__breakage-notes-panel_for_single_height_by_groovecoder_ _pull_request__148_ _mozilla_blok_ _github_and_unable_to_disable_tracking_protection_for_a_page_via_toggle_ _issue__150_ _mozilla_blok](https://cloud.githubusercontent.com/assets/557895/18525558/db5d62a4-7a71-11e6-9588-fba1eaaaf3a4.png)

**Comment by groovecoder** [comment]
Thanks for filing. I've seen this before too. I think it's intermittent, but I can try to find a fix for it anyway. E.g., I suspect the site is somehow lingering in the `allowedHosts` list in the add-on storage. I might try changing the "re-enable" logic to loop thru all the hosts in the list and delete any entries that match. So it would clear out any lingering entries too.

**Comment by groovecoder** [comment]
Note: a fix is available in https://github.com/mozilla/blok/pull/191 but I'm closing this without merge, because I'm afraid of the code churn's effect on other users, and I think only us early devs ever got into this bug state.
