### ISSUE TITLE
Tracking Protection toggle sometimes disappears

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#151]
Ref: https://github.com/mozilla/blok/pull/148#issuecomment-247147745

> Looks good. I notice that if I initiate a report, then go back, I [sometimes] lose the ability to toggle Tracking protection:

> ![reddit__the_front_page_of_the_internet](https://cloud.githubusercontent.com/assets/557895/18529350/8bbd3d7c-7a81-11e6-89f6-b9ed25986bbf.png)

> And now that I say that, and go to record a GIF, I cannot reproduce.

---

Ref: https://github.com/mozilla/blok/pull/148#issuecomment-247148921

> Very clumsy video, but I was eventually to get back into that state of not being able to toggle tracking protection.

> ![blok-148](https://cloud.githubusercontent.com/assets/557895/18529473/0f745164-7a82-11e6-951f-a9734b93bf0d.gif)

**Comment by groovecoder** [comment]
This is/was an old aspect of the "back" button. It's been removed in the latest version of the add-on, so this bug is gone with it.
