### ISSUE TITLE
Do not block iframe requests to one of its ancestors' top-level domains

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blok#16]
Sub-task of #11 ...

The platform code also treats the following load as first-party:

- top-level page is `www.facebook.com`
- there is an iframe to `game.superfarmers.com`
- that iframe loads `sdk.facebook.com/leaderboard.js`

While `game.superfarmers.com` and `sdk.facebook.com` are third-parties, `sdk.facebook.com` is considered first-party with the top-level page (`www.facebook.com`) so we load it.

See http://searchfox.org/mozilla-central/rev/ef24c234ed53b3ba50a1734f6b946942e4434b5b/netwerk/base/nsChannelClassifier.cpp#95-117

**Comment by groovecoder** [comment]
@fmarier: do we have bugs for the platform-level implementation of this? So I can dig into the details here and get some good test urls for it?

**Comment by groovecoder** [comment]
@fmarier - I made https://github.com/mozilla/blok/commit/b4147d441379fab86cd8107041fd97be56abb2ef which should work for this. What's a good test page for it though?

**Comment by fmarier** [comment]
> What's a good test page for it though?

I don't think we have a proper test page for this, we used a Facebook game when we landed that fix. It would however be good to create a test page that we can hold on to.

You could submit a PR against mozilla/trackertest to add a page on `itisatracker.com` (it's an alias to that repo which is on the Disconnect list) which iframes a non-tracking domain which in turn loads <https://itisatracker.com/tracker.js>.

**Comment by fmarier** [comment]
> Do we have bugs for the platform-level implementation of this?

The platform bug was https://bugzilla.mozilla.org/show_bug.cgi?id=1108017

**Comment by groovecoder** [comment]
@fmarier I submitted https://github.com/mozilla/trackertest/pull/12 for this.

**Comment by groovecoder** [comment]
Need to be sure to [test this iframe logic in combination with the entity blocklist logic](https://github.com/mozilla/blok/pull/23#issuecomment-232802824).

I.e., `youtube.com` iframes `pubads.g.doubleclick.net`, which makes requests to `securepubads.g.doubleclick.net`, `s0.2mdn.net`, and/or `tpc.googlesyndication.com`. Need to allow all those requests, since they are all in the same entity as the top-frame youtube.com "Google" entity.

**Comment by groovecoder** [comment]
Fixed in https://github.com/mozilla/blok/commit/840554a035f54ae6b44e4e9f7b6907efc2706714
