### ISSUE TITLE
Blurry icon in location bar (HiDPI issue)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/blok#166]
The shield icon is very blurry on my MacBook with Retina display. A icon with a higher resolution should be used for HiDPI displays.

**Comment by fangshih** [comment]
Update the shield icon assets with higher resolution
[#166-Shield icon assets.zip](https://github.com/mozilla/blok/files/532673/166-Shield.icon.assets.zip)

**Comment by johngruen** [comment]
@groovecoder this is ready to go

**Comment by groovecoder** [comment]
Oh sorry I didn't notice the assets connected here. I'll get them added.
