### ISSUE TITLE
Layout of "Report a problem" broken

### ISSUE THREAD

**Issue by rugk** [mozilla/blok#168]
I could reproduce this issue with all other add-ons disabled.
FF 49.0.1

![brokenerrorreport](https://cloud.githubusercontent.com/assets/11966684/18928542/e3a0695c-85c0-11e6-893f-04c581a66c98.png)

It also makes it impossible to click on the "Submit" button, which presumably is at the bottom.

**Comment by groovecoder** [comment]
Thanks for the report. Can you specify your platform: Windows, Mac, or Linux?

**Comment by rugk** [comment]
Linux x64 (Debian)

**Comment by groovecoder** [comment]
Thanks. This is a duplicate (& verification) of https://github.com/mozilla/blok/issues/147. 😢 I will have to get to a Linux box next week to debug it, unless someone else wants to help on it.

**Comment by rugk** [comment]
I'll can help with debugging if you can give me a hint how to get the debugging console (inclusive the inspector) to point to the UI element. (I tried it through `about:debugging`, but unfortunately there is no inspector when using the dev tools in this way.)

**Comment by groovecoder** [comment]
You can follow [the "Development Environment" section of the README](https://github.com/mozilla/blok#development-environment).

**Comment by groovecoder** [comment]
And be sure to look at the [Debugging popups section of the Browser Toolbox doc](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox#Debugging_popups).

**Comment by rugk** [comment]
Thanks for the tips.

So basically the issue is that the width of the labels has been set to `220px` in a popup.css. Se this gif for details
![hihi](https://cloud.githubusercontent.com/assets/11966684/18933387/ccd50a16-85d4-11e6-9f69-669d728e78ad.gif)

The big left space still looks bad afterwards, but this would at least make the options useable.
