### ISSUE TITLE
enabling error

### ISSUE THREAD

**Issue by DGIFFORD2003** [mozilla/blok#169]
Tracking Protection will not enable when trying to be a test pilot member

**Comment by pprincetta** [comment]
I cannot enable this app for some reason

**Comment by DGIFFORD2003** [comment]
After restarting the browser, I gave it another try and they worked for me after all.  Thanks anyway


DOUGLAS A GIFFORD
________________________________

**Comment by ckprice** [comment]
Closing out in favor of https://github.com/mozilla/testpilot/issues/1474
