### ISSUE TITLE
update color of notification bar

### ISSUE THREAD

**Issue by ashgrigas** [mozilla/blok#17]
please make gradient of bar:
gradient #414141  to #606060 

and styling to match these specs:

1px dropshadow

[4:03]  
.Infobar {
 background-image: -moz-linear-gradient( 90deg, rgb(65,65,65) 0%, rgb(96,96,96) 100%);
 background-image: -webkit-linear-gradient( 90deg, rgb(65,65,65) 0%, rgb(96,96,96) 100%);
 background-image: -ms-linear-gradient( 90deg, rgb(65,65,65) 0%, rgb(96,96,96) 100%);
 box-shadow: 0px 1px 0px 0px rgba(42, 42, 42, 0.004),inset 0px 1px 0px 0px rgba(255, 255, 255, 0.1);
 position: absolute;
 left: 2396px;
 top: 607px;
 width: 1200px;
 height: 27px;
 z-index: 2081;
}

**Comment by groovecoder** [comment]
Thanks. I've got a couple of changes in flight that re-arrange lots of the code-base, so I'm going to wait until those are merged to fix this to avoid conflicts.

**Comment by groovecoder** [comment]
Is there a screenshot of what this is supposed to look like? So I can make sure I have it right?

**Comment by ashgrigas** [comment]
yeah this is bryan's earlier mock using that color:
https://www.dropbox.com/s/j0ftrn7rdk1tlg4/TP%20Add-on%20Doorhanger%20copy%202.png?dl=0

On Tue, Jul 12, 2016 at 11:24 AM, luke crouch <notifications@github.com>
wrote:

> Is there a screenshot of what this is supposed to look like? So I can make
> sure I have it right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/blok/issues/17#issuecomment-232083347>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AI_-mDetBdRPQ0u13tYVdgCG1OI1iC4Mks5qU7G_gaJpZM4JJWnt>
> .
>



-- 
Aislinn Dewey Grigas
User Experience Design Consultant
www.aislinndewey.com
978.930.3729
------------------------------
<http://www.linkedin.com/in/aislinn>   <http://www.twitter.com/ashdewey>
<http://www.facebook.com/ashdewey>

**Comment by groovecoder** [comment]
Cool, thanks. From where is the rest of that `.Infobar` styling? It doesn't include `color` and the absolute positioning seems designed for a static image/page.
