### ISSUE TITLE
Addressbar Icon looks ugly in Dark theme (e.g. Firefox Developer Edition)

### ISSUE THREAD

**Issue by jnachtigall** [mozilla/blok#175]
A matter of taste, but I think the pink on black looks not very nice:
![2016-09-30 14_54_46-linux und open source _ heise online - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/18992357/2899b8de-871e-11e6-9599-6fd82e7c7d31.png)

Just let it be the light grey color like the Reload or Readers Mode buttons. This would integrate which nicer.

**Comment by jnachtigall** [comment]
And it would be nice if it wasn't looking like p0rn mode (pink / private browsing), because I use this at work, too ;) There are many reasons running a browser in "disconnect" / blok mode, but not in private mode...

**Comment by groovecoder** [comment]
Personally, I like(d) our TxP full-color, full-resolution shield:

![banner](https://cloud.githubusercontent.com/assets/71928/19310405/84cadf86-904f-11e6-9bc9-c1bccbcb0c8b.png)

But it probably doesn't work at that small resolution in the location bar.

**Comment by jnachtigall** [comment]
Jeez, that's even more p0rn mode ;) I like the Android shield logo (on Firefox for Android Nightly, there's a nice logo in the address bar if you enable Tracking Protection)

**Comment by fangshih** [comment]
As for the consistency with light theme browser, we can try one with light purple-ish color, so it can keep the color toward purple/pink color and also noted user they are in private protecting mode without being too "loud" as you mentioned. 
![tp_darkmode-1](https://cloud.githubusercontent.com/assets/4862573/19434217/d74732e6-9496-11e6-85bd-f76bbe7eef60.png)

**Comment by fangshih** [comment]
Update the shield icon assets with better visibaltiy. Let me know what you guys think. Thanks! 
[glyph-trackingProtection-dark.zip](https://github.com/mozilla/blok/files/535469/glyph-trackingProtection-dark.zip)

**Comment by johngruen** [comment]
@fangshih i think we could do grey to match other icons there.

**Comment by fangshih** [comment]
I see. I was a little worry it's not popping out enough. 👻 
I updated the icon to grey, here are the icon assets. Thanks!
[glyph-TP-dark.zip](https://github.com/mozilla/blok/files/565917/glyph-TP-dark.zip)

**Comment by johngruen** [comment]
@groovecoder i guess we could do somthing clever here like change the pageAction icon if `window[lwthemetextcolor] = "dark"` or something like that. Anyway, assets are ready, so changing the labels.

**Comment by groovecoder** [comment]
Before I get into `window[lwthemetextcolor]`, here's screen-shots of all the variations.

## Grey Icon
<img width="720" alt="tp-disabled-dark-grey" src="https://cloud.githubusercontent.com/assets/71928/19941365/db250820-a0fd-11e6-8582-c09570731ac6.png">
<img width="720" alt="tp-enabled-dark-grey" src="https://cloud.githubusercontent.com/assets/71928/19941366/db281f9c-a0fd-11e6-87e1-3f91297f7903.png">
<img width="720" alt="tp-enabled-light-grey" src="https://cloud.githubusercontent.com/assets/71928/19941367/db297eaa-a0fd-11e6-8df8-d4c3b672d499.png">
<img width="720" alt="tp-disabled-light-grey" src="https://cloud.githubusercontent.com/assets/71928/19941368/db2cd302-a0fd-11e6-8573-df0dab2de625.png">

## Light Purple Icon
<img width="720" alt="tp-enabled-light-purple" src="https://cloud.githubusercontent.com/assets/71928/19941391/ed94089e-a0fd-11e6-8860-bc65c5e06d80.png">
<img width="720" alt="tp-disabled-light-purple" src="https://cloud.githubusercontent.com/assets/71928/19941390/ed92d938-a0fd-11e6-80bc-aa74e11c266c.png">
<img width="720" alt="tp-enabled-dark-purple" src="https://cloud.githubusercontent.com/assets/71928/19941389/ed924202-a0fd-11e6-80de-3e06ef3d009c.png">
<img width="720" alt="tp-disabled-dark-purple" src="https://cloud.githubusercontent.com/assets/71928/19941392/ed948ea4-a0fd-11e6-8857-71ebc4c52364.png">

I personally like using the light purple icon for everything b/c it's consistent, it pops out in both color schemes, and it's simpler. (Less code logic == less potential for bugs later)

@johngruen - does light purple look good here?

**Comment by johngruen** [comment]
yeah, light purple is good! SHIPIT!
