### ISSUE TITLE
Could be this be an alternative for Disconnect in the future?

### ISSUE THREAD

**Issue by zer09** [mozilla/blok#178]
Could be this be a good alternative for Disconnect app? It seems Disconnect has no update for more than a year and it doesn't support e10s.

**Comment by groovecoder** [comment]
We get our upstream block-list from Disconnect itself.

The primary goal of this add-on is to collect problem & breakage data to learn the most common problems & breakages users experience with request-blocking Tracking Protection enabled.

**Comment by zer09** [comment]
@groovecoder Thanks.

BTW based on your second sentence, does it mean that Tracking Protection can be just only enable in Private Browsing after the test pilot for this app will be done or it will be?

**Comment by groovecoder** [comment]
We're not deciding any of that right now 😉 Just getting problem & breakage data to learn new ideas for tracking-protection & privacy tech.

**Comment by groovecoder** [comment]
Closing this issue. Thanks for asking this. We're focusing on break-fixes and measurement data right now.
