### ISSUE TITLE
[docs] Comparison with ublock origin, eff privacy badger, ghostery

### ISSUE THREAD

**Issue by jnachtigall** [mozilla/blok#180]
Users interested in this experiment will probably already have another addon like 
- ublock origin
- eff privacy badger
- ghostery
- ad block plus 

running (like I do). 

I wonder what makes this experiement technically, UX-wise and conceptional any different from these well-known addons? Why should I run it instead (or next to) any of the above? What are its USPs? (Maybe, Also how does it compare to the Tracking Protection that is already enabled in Firefox for Android Nightly?)

This were the question that immediately jump at me when seeing this experiment and I could not find any documentation on it. It would be nice if a bit would be answered in the README.md or some linked wiki page.

**Comment by rugk** [comment]
* ublock origin -> is mostly an ad-blocker, but can block tracking tools too, yes
* eff privacy badger -> works with algorithms, Blok however just uses a static [block lists](https://support.mozilla.org/en-US/kb/tracking-protection-pbm) by Disconnect
* ghostery -> [probably not a good idea](https://lifehacker.com/ad-blocking-extension-ghostery-actually-sells-data-to-a-514417864), also uses a block list
* ad block plus -> add-blocker, does not blcok tracking tools by default

> (Maybe, Also how does it compare to the Tracking Protection that is already enabled in Firefox for Android Nightly?)

It is the same. Actually tracking protection is already enabled in Firefox **stable**, but it only is activated in the private browsing mode. the only thing this experiment - basically - does is, also enabling it in the "usual" browsing mode.

**Comment by groovecoder** [comment]
We could uplift some info into the codebase, but [the Test Pilot experiment page](https://testpilot.firefox.com/experiments/tracking-protection) (tries to) make the value add clear; it:

> lets you help us understand where Tracking Protection breaks the Web so that we can improve it for all Firefox users.

The primary goal of this add-on experiment is to create a feedback loop for tracking protection users to provide data on problems & breakage, so we (Mozilla) can learn how to improve tracking protection technologies in ways that maximize user privacy AND minimize web breakage.

The other privacy add-ons are great tools as well. The ability to report website problems & breakages is the key difference here. In fact, we deferred a number of other features in favor of simplicity and to make the feedback mechanism the primary focus of the add-on.

Assigning to @johngruen for a decision here.

**Comment by johngruen** [comment]
@groovecoder yeah, i'd actually be good just adding your comments here (or a cleaned up version thereof to an FAQ file in this repo.

**Comment by johngruen** [comment]
Also, linked to the main readme file

**Comment by johngruen** [comment]
I can take a crack at a PR on this mañana
