### ISSUE TITLE
Console error: "Please specify whether you want browser_style or not in your page_action options."

### ISSUE THREAD

**Issue by rugk** [mozilla/blok#182]
This is shown at startup when I start Firefox from the console.

```
1475679053122	addons.webextension.blok@mozilla.org	WARN	Please specify whether you want browser_style or not in your page_action options.
```

**Comment by groovecoder** [comment]
Thanks for the bug report.

**Comment by SoftVision-EmilPasca** [comment]
I have manage to reproduce this on Mac OS 10.11, Ubuntu 16.04 x64 and Windows 10 x64 using Firefox 49.0.1 with the latest testpilot and blok addons installed.
The issue is also reproducible with Nightly 52.0a1 on Ubuntu 16.04 x64, on Windows and Mac it isn't.
