### ISSUE TITLE
TestPilot Tracking protection unable to install

### ISSUE THREAD

**Issue by Menimue** [mozilla/blok#185]
Thanks for your email groovecoder and I tried again to install but same notice again saying ..'unable to install at this time, try again later'
I have tried many times later several times a day over the last week daily and still cannot install.
I'm using ff.49.
Can anyone give me a clue as to what may be causing this please.
I have Smart https add-on installed

**Comment by groovecoder** [comment]
Have a look at https://github.com/mozilla/testpilot/issues/1474 ...

Does that sound like your issue? If so, a fix may be incoming on the Test Pilot side.

**Comment by groovecoder** [comment]
Closing as an effect/duplicate of https://github.com/mozilla/testpilot/issues/1474. Please continue discussion there.

**Comment by rabimba** [comment]
That does look like my problem. Though I could use page shot just fine. But Tracking protection is not working.
