### ISSUE TITLE
Tracking Protection description seems to be outdated, mentions about old "notification bar"

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/blok#186]
[Affected versions]:
- Nightly 51.0a1
- Blok v1.0.1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Steps to reproduce]:
1. Got to Tracking Protection experiment page: https://testpilot.firefox.com/experiments/tracking-protection
2. Observe the second phrase of the second paragraph from experiment description.

[Expected result]:
- "As you browse, use the Tracking Protection shield icon in the address bar to tell us which sites work well with Tracking Protection and which don’t".

[Actual result]:
- "As you browse, use the convenient notification bar at the top of the page to tell us which sites work well with Tracking Protection and which don’t."

[Notes]:
- Added a screen shot with the issue:
  ![tpx_page_issue](https://cloud.githubusercontent.com/assets/20083658/19198298/13507770-8cc7-11e6-8764-a3387bd5d669.jpg)

**Comment by groovecoder** [comment]
@johngruen this is for you, right?

**Comment by johngruen** [comment]
Resolved, fixed.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible on https://testpilot.dev.mozaws.net/experiments/tracking-protection .
