### ISSUE TITLE
Social media fingerprint

### ISSUE THREAD

**Issue by rugk** [mozilla/blok#194]
Have a look at https://robinlinus.github.io/socialmedia-leak/. It is a special tracking mechanism, but as I discovered [FF blok already helps against some services](https://github.com/RobinLinus/socialmedia-leak/issues/5).

It would however, be nice if it could block all of them.

**Comment by rugk** [comment]
Actually I see that it literary blocks the favicons:
![favicoblock](https://cloud.githubusercontent.com/assets/11966684/19322052/d09535ca-90b7-11e6-99b8-acba61d7358e.png)

In this case that's wanted, of course.

**Comment by groovecoder** [comment]
That's a great site and point. A couple other Mozilla folks shared this to me on IRC too. 😄 

Blok/Tracking Protection is based on a block-list of known **tracking** domains. While social media fingerprinting is a privacy vulnerability, it's a different "threat model" than 3rd-party tracking.

So, I'm going to close this issue in this repo, but thank you for sharing this social media fingerprint technique. It's an interesting area, and I'm almost tempted to check some Mozilla platforms (MDN, SUMO, Bugzilla, etc.) to see if they are vulnerable to this. Almost. 😉
