### ISSUE TITLE
Embedded tweets are not displayed correctly

### ISSUE THREAD

**Issue by ziww** [mozilla/blok#195]
Steps to reproduce:
1. Open any page with embedded tweets
 Example: https://www.buzzfeed.com/kellyoakes/picture-tweets-to-restore-your-faith-in-science
2. Tweets are not displayed correctly
3. Toggle to disable
4. Tweets are shown correctly

**Comment by groovecoder** [comment]
Thanks for the issue. Since this is a breakage report, did you submit the breakage via the built-in UI too? That way we can analyze it quantitatively against other breakage reports.

**Comment by ziww** [comment]
I don't think I did, but I'll do it. Thanks for the tip!

**Comment by groovecoder** [comment]
I'm going to close this issue to keep this repo issue list about the bugs/issues with the code, functionality, and UX. We're getting the breakage data via the Telemetry probes in the feature.
