### ISSUE TITLE
After closing the button tooltip, the context of report is lost

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/blok#197]
How to reproduce:
- Open a website where you want to report a problem.
- Click the icon in address bar.
- Click report a problem.
- Choose the problem (e.g. button).
- Click elsewhere, or just wait until some other window steals focus (like Thunderbird event notification).
- Now the report is closed.
- Click the icon in address bar again.
- You need to start with the report from scratch.

**Comment by groovecoder** [comment]
Thanks for the issue.

@johngruen and/or @ashgrigas - should we classify this a bug (i.e., "popup blur event clears report state") or a UX enhancement (i.e., "preserve report state when popup loses focus")?

**Comment by youwenliang** [comment]
I also notice that after clicking "report a problem" and dismissing the doorhanger without hitting submit, it will count as you reported a problem.

**Comment by groovecoder** [comment]
@youwenliang that was discussed in https://github.com/mozilla/blok/issues/159 and should be "fixed" in https://github.com/mozilla/blok/pull/183. We need to make a new release to deploy it.

**Comment by johngruen** [comment]
@groovecoder yeah, maybe we should maintain any inputs until the user submits or navigates to another page.

**Comment by MikkCZ** [comment]
As the experiment is closed, closing this issue too.
