### ISSUE TITLE
Implement Safe Browsing hostname canonicalization

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blok#2]
See https://developers.google.com/safe-browsing/v4/urls-hashing#canonicalization

* [x] Remove all leading and trailing dots
* [x] Replace consecutive dots with a single dot
* [x] If the hostname can be parsed as an IP address, normalize it to 4 dot-separated decimal values. The client should handle any legal IP-address encoding, including octal, hex ...
  * [ ] and fewer than four components
* [x] Lowercase the whole string

**Comment by groovecoder** [comment]
@fmarier - do you have JS code for hostname canonicalization already in the platform level?

**Comment by fmarier** [comment]
I don't think we have JS code for this, but given the Disconnect list only includes domains (no paths), it should be pretty trivial to just have a loop like this:

```
while (url.parts > 1) :
  check(url)
  url.popFirstPart()
```

So `www.foo.bar.com` would lead to:

1. check("www.foo.bar.com")
2. check("foo.bar.com")
3. check("bar.com")

**Comment by groovecoder** [comment]
@fmarier I finally finished the blok -> testpilot -> telemetry code and I'm back into this. To refresh my memory ...

We don't need to canonicalize the hosts in `disconnect-blocklist.json`right? They are already in the canonicalized form, so we only need to canonicalize the requests' hosts to check against the blocklist?

**Comment by fmarier** [comment]
> We don't need to canonicalize the hosts in disconnect-blocklist.jsonright? They are already in the canonicalized form, so we only need to canonicalize the requests' hosts to check against the blocklist?

Correct.

**Comment by groovecoder** [comment]
I'm closing this. Added https://github.com/mozilla/blok/issues/21 for the last bit of IP address canonicalization.
