### ISSUE TITLE
Change copy/text of "notes" field

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blok#205]
Many of the notes submitted by users are saying things like

* "Because when I turn it off the pictures appear."
* "I can toggle the problem."
* "When i turend it off everyhing is fine!"
* "Problem toggles on/off."
* "With TP disabled, display was corrected."
* "I can toggle the image problem on and off."
* "turning it off and reloading the page and the images are fine. turning back on and images are again broken"

We should change the text/copy from "Why do you think Tracking Protection caused this problem?" to "Please tell us more details about the problem."

**Comment by johngruen** [comment]
Makes sense to me. These answers are sort of recursive.
