### ISSUE TITLE
Block tracking but not advertising

### ISSUE THREAD

**Issue by terrycloth** [mozilla/blok#211]
Web advertising is what does most(?) of the invasive tracking of user behavior. Most ad-blockers let you whitelist a domain, and I normally do so for the websites I frequent. When considering the overlap in functionality between an ad blocker and a tracking blocker, I started wondering: Is it theoretically possible to allow websites to display ads and earn revenue but still block the user-tracking that goes with it?

**Comment by groovecoder** [comment]
Thanks for the issue. You make an important - and very large - point. 😉

Smart folks like [Don Marti](http://zgp.org/~dmarti/) are blogging about this a lot, and there are [entire web software startups](https://brave.com/publishers.html) exploring this too.

So, I'm going to close this particular issue, but I encourage you to keep asking this question and get involved with some of the larger efforts and projects out there.

**Comment by groovecoder** [comment]
Oh, and Mozilla Firefox content security team and engineers have lots of ideas here too, including [healthier cookies](https://public.etherpad-mozilla.org/p/healthiercookies), [referrer improvements](https://public.etherpad-mozilla.org/p/referrerimprovements), and [other recommended prefs](https://public.etherpad-mozilla.org/p/securefox) to improve security & privacy in Firefox. All of those etherpads contain links to lots of the bugs.

**Comment by terrycloth** [comment]
Interesting! I was sorta hoping Tracking Protection might be able to offer a solution in selectively blocking tracking but leaving the ads --- at some point in the future. I guess that's maybe outside the scope of this project though?

I don't know how it would work technically. But I was already aware of Brave, and it seems to me like *that* could have been implemented as an extension instead of a whole 'nother Chromium clone.
