### ISSUE TITLE
Update notification bar styling and behavior to match updated design spec

### ISSUE THREAD

**Issue by ashgrigas** [mozilla/blok#22]
## Design:
https://www.dropbox.com/s/nbkkatjfhhr2xbj/sk3.png?dl=0

![blok-notification-bar-style-behavior](https://cloud.githubusercontent.com/assets/71928/16846115/ced64b1e-49b0-11e6-840b-d00601982387.png)

form controls assets are here:
http://people.mozilla.org/~shorlander/styleguide/styleguide-buttons/form-controls.html

## Copy:
[![blokr-copy-reference](https://cloud.githubusercontent.com/assets/71928/16959328/2354cfa6-4daa-11e6-8488-76e6bf67f5df.png)](https://docs.google.com/presentation/d/1_O-A3cKMS4cto51Ld5uiyEmXRZ1HxGL_RmHQNzR0atg/edit?ts=578e5262#slide=id.p)

https://docs.google.com/spreadsheets/d/19JAW3XkhfkRbAeGKia3loRMZou96_HUVoBxSh3f1oEQ/edit?ts=578e51f8#gid=0

**Comment by groovecoder** [comment]
Thanks @ashgrigas. Do you have any CSS styles or other assets you used to create these?

**Comment by ashgrigas** [comment]
This was made based on the notification bar and button styling we use
currently in release and the modal can be seen in the preferences panel of
Firefox. Same goes for the radio buttons.

http://people.mozilla.org/~shorlander/styleguide/styleguide-buttons/form-controls.html



On Thu, Jul 14, 2016 at 11:51 AM, luke crouch <notifications@github.com>
wrote:

> Thanks @ashgrigas <https://github.com/ashgrigas>. Do you have any CSS
> styles or other assets you used to create these?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/blok/issues/22#issuecomment-232707059>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AI_-mPTzsZA1Kf0zkS2oGTtx4zBuw5V-ks5qVlsCgaJpZM4JLsN4>
> .
>



-- 
Aislinn Dewey Grigas
User Experience Design Consultant
www.aislinndewey.com
978.930.3729
------------------------------
<http://www.linkedin.com/in/aislinn>   <http://www.twitter.com/ashdewey>
<http://www.facebook.com/ashdewey>
