### ISSUE TITLE
Implement final Telemetry ping payload format

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blok#28]
Discussion also happening at https://bugzilla.mozilla.org/show_bug.cgi?id=1288196

# Questions we want to ask the data
* What are the most popular broken sites?
  * How are they broken?
    * How might we fix them?
  * Is there an anti-blocker in the page
* Which trackers are most commonly involved with breakage?
  * What tracking techniques are they using?
* How much time & bandwidth are users wasting with trackers?

# Currently:
## "Report a problem"
![blok-report-problem](https://cloud.githubusercontent.com/assets/71928/16968485/c249d852-4dd4-11e6-9f96-32fb4dac9336.png)
```{"originDomain":"www.redditmedia.com","trackerDomains":["ssl.google-analytics.com","www.google-analytics.com","sb.scorecardresearch.com"],"feedback":"page-problem"}```

## Breakage report
![blok-breakage-report](https://cloud.githubusercontent.com/assets/71928/16968543/2a367fe2-4dd5-11e6-8c94-94694fe4cd63.png)
```{"originDomain":"www.redditmedia.com","trackerDomains":["ssl.google-analytics.com","www.google-analytics.com","sb.scorecardresearch.com","static.adzerk.net","z.moatads.com"],"breakage":"layout","notes":""}```

## "This page works well"
![bloke-page-works](https://cloud.githubusercontent.com/assets/71928/16968516/f592d006-4dd4-11e6-84d4-dd0eaaf5fd27.png)
```{"originDomain":"www.redditmedia.com","trackerDomains":["ssl.google-analytics.com","www.google-analytics.com","sb.scorecardresearch.com","static.adzerk.net","z.moatads.com","static.adzerk.net","z.moatads.com"],"feedback":"page-works"}```

# What's possible:

## Blocked requests
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/WebRequest/onBeforeRequest#details

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/WebRequest/onBeforeSendHeaders#details

## Allowed requests
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/WebRequest/onCompleted#details

**Comment by georgf** [comment]
Should the "Breakage report" payload also include, say, "feedback":"breakage"?
That would make it more consistent with the other two.

**Comment by groovecoder** [comment]
So ...
```
{
  feedback: 'page-problem|page-works|breakage',
  breakage: 'images|video|layout|buttons|other',
  notes: ${notes},
  originDomain: ${origin},
  trackerDomains: [${domain1}, ${domain2}, ...]
}
```
With `breakage` and `notes` both optional?

**Comment by groovecoder** [comment]
@georgf - does the payload in the comment look good? If so, I'll plan to implement that as our final format.

**Comment by groovecoder** [comment]
@clouserw - you said that these pings and payloads will go into an "ignore" bucket somewhere in the telemetry pipeline? Any chance I can see that somewhere so I can test this end-to-end?

**Comment by wresuolc** [comment]
I don't have access to that bucket.  Rob or Rebecca would I think.

**Comment by clouserw** [comment]
Proposed format at https://github.com/mozilla/blok/pull/89 .  Comments welcome.
