### ISSUE TITLE
Duplicate key 'Adsrevenue' in disconnect-entitylist.json

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#37]
Playing with JSON validation using [**eslint-plugin-json**](http://npm.im/eslint-plugin-json) and it spotted one error (`bad-json`) in disconnect-entitylist.json:

```sh
$ ./node_modules/.bin/eslint --ext=.json .

/Users/pdehaan/dev/github/mozilla/blok/disconnect-entitylist.json
  1153:5  error  Duplicate key 'Adsrevenue'  bad-json

✖ 1 problem (1 error, 0 warnings)
```

Code in question is:

```json
    "Adsrevenue": {
        "properties": [
            "adsrevenue.net"
        ],
        "resources": [
            "adsrevenue.net"
        ]
    },

    "Adsrevenue": {
        "properties": [
            "adsnative.com"
        ],
        "resources": [
            "adsnative.com"
        ]
    },
```

I'd guess that in this case the .net domain is getting overwritten by the .com domain entry. Or not, what do I know, man.

And my minimal .eslintrc file is:
```yaml
extends: eslint:recommended

plugins:
  - json
```

If we're getting this from an upstream provider, we may be out of luck &mdash; but still worth investigating and possibly filing a bug with them.

**Comment by groovecoder** [comment]
I looked for a way to file this up-stream to Disconnect but I couldn't find one. FWIW, their https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json only includes adsrevenue.net. adsnative.com also seems to be operational, but I don't know if/how to verify if they are the same entity as adsrevenue.net. 😒

**Comment by groovecoder** [comment]
Note: this is fixed in our own upstream repo for the entity list:

https://github.com/mozilla-services/shavar-prod-lists/pull/19

Need to grab the latest entity list from there to really call this issue fixed though.

**Comment by groovecoder** [comment]
Fixed in https://github.com/mozilla/blok/commit/ab6f2495b6701a3d74ccd1cea60b84ccad5c66db
