### ISSUE TITLE
Install Foundation instead of including in repo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#45]
Per https://github.com/mozilla/blok/pull/33#discussion_r71975541

Currently we're including 3rd party Foundation CSS code in the repo (see [/css/foundation.min.css](https://github.com/mozilla/blok/blob/567eef8b2a1471aa62bc590788578651775eda42/css/foundation.min.css)).

It'd be nice if we included this via something like Bower or Node as a dependency.

Closest I can guess, we could do something like:

```sh
$ npm i foundation-sites -D
```

Then add a package.json `postinstall` hook to copy the file into /css/:

```js
"postinstall": "cp ./node_modules/foundation-sites/dist/foundation.min.css css/foundation.min.css",
```

Or, we could write some Node script to copy the file, but that seems a bit more verbose (although probably a bit more cross-platform friendly):

```js
const fs = require('fs')
const path = require('path')

const cssPath = require.resolve('foundation-sites/dist/foundation.min.css')
const cssDest = path.join(__dirname, '..', 'css', 'foundation.min.css')

fs.createReadStream(cssPath).pipe(fs.createWriteStream(cssDest))
```

**Comment by groovecoder** [comment]
Let's stick with node. I'd like to avoid adding any other toolchains (bower, gulp, etc.) unless we absolutely have to.

**Comment by groovecoder** [comment]
Oh, I think I tried using the npm-installed foundation-sites package, but it isn't updated to Foundation 6 yet?

**Comment by groovecoder** [comment]
Huh, looks like foundation-sites is up to 6.2.3 now. That being the case, I'd prefer the npm + postinstall approach.
