### ISSUE TITLE
actionRequests is undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#51]
```
$ git rev-parse HEAD # cb8d191c9bbf92f957441322f0e9ac59d5d1cd90
```

### Steps to reproduce:
1. `$ rm -f web-ext-artifacts/*`
1. `$ npm run build-dev`
1. Drag generated web-ext-artifacts/blok-0.1.2.zip into Firefox Nightly about:addons to install.
1. Browse around GitHub (or whatever)

### Actual results:

> `actionRequests is undefined` (background.bundle.js:182)

> ```js
log('blocked ' + actionRequests.length + ' requests: ' + actionRequests)
```
> &mdash; via [/js/background.js:181](https://github.com/mozilla/blok/blob/84ad1142a9fe006cf89d2299d2e902521eb1d1b8/js/background.js#L181)

![browser_console](https://cloud.githubusercontent.com/assets/557895/17149376/e240e204-531f-11e6-89ed-1f3ad5e7c777.png)

**Comment by groovecoder** [comment]
This is a secondary effect of https://github.com/mozilla/blok/issues/50
