### ISSUE TITLE
blockedRequests[requestTabID] is undefined

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#52]
```
$ git rev-parse HEAD # cb8d191c9bbf92f957441322f0e9ac59d5d1cd90
```

### Steps to reproduce:
1. `$ rm -f web-ext-artifacts/*`
1. `$ npm run build-dev`
1. Drag generated web-ext-artifacts/blok-0.1.2.zip into Firefox Nightly about:addons to install.
1. Browse around GitHub (or whatever)

### Actual results:

> blockedRequests[requestTabID] is undefined (background.bundle.js:145)

> ```js
blockedRequests[requestTabID].push(requestTopHost)
```
> &mdash; via [/js/background.js:144](https://github.com/mozilla/blok/blob/84ad1142a9fe006cf89d2299d2e902521eb1d1b8/js/background.js#L144)

![browser_console](https://cloud.githubusercontent.com/assets/557895/17149472/4c71a14a-5320-11e6-915a-b64dd919894c.png)

**Comment by groovecoder** [comment]
Another effect of https://github.com/mozilla/blok/issues/50
