### ISSUE TITLE
Save reported results

### ISSUE THREAD

**Issue by rbillings** [mozilla/blok#70]
It would be ideal if pages saved reported data instead of clearing it upon refresh or a new tab view.

**Comment by groovecoder** [comment]
Can you say more? Like, when a user sees saved reported data (in the notification bar?), show them ___, so they can ___ ?

**Comment by rbillings** [comment]
Clarification: each time the user views a page the Blok header displays the default status- regardless of whether or not they had previously said it worked well or had a problem. It would be nice if a user's submitted response was preserved so that when they see the same site again they don't need to re-submit if it works well or not. So show them the response they already gave when they view the site.

**Comment by groovecoder** [comment]
Ah, yeah I thought about this but a refreshes on the same urls could be different. I.e., http://www.tulsaworld.com/news/capitol_report/governor-s-proposal-for-special-session-on-teacher-pay-raises/article_c0bf0b11-8bae-544c-bea9-6a78617e1f90.html could work during a page-view, but be broken on the next page-view, depending if the site changes out what JS is run on the page.

**Comment by rbillings** [comment]
Since the doorhanger displays previously submitted responses, and is no longer always displayed- I will go ahead and close this.
