### ISSUE TITLE
Private browsing not able to enable/disable Blok

### ISSUE THREAD

**Issue by rbillings** [mozilla/blok#74]
Previously I was able to enable/disable Blok using private browsing windows- as of today, both Nightly and Dev Edition are refreshing the page when you click on the disable/enable link but the status is not updating.

**Comment by groovecoder** [comment]
Damn, this is a regression on more than just PBM windows. I'll check it out.

**Comment by groovecoder** [comment]
Hmm ... had trouble reproducing this behavior in DE ... but I found another bug

Steps to (not) reproduce:
1. `git checkout master`
2. `npm install`
3. `./node_modules/.bin/web-ext run --firefox-binary=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin --firefox-profile=Blok`
4. Open tulsaworld.com
  * See Blok toolbar
5. Click "Disable Blok on this site"
  * Page refreshes; Blok toolbar shows " Blok is disabled. Parts of this site my be tracking your activity. Enable Blok on this site."; a bunch more ads show
6. Click "Enable Blok on this site."
  * Page refreshes; Blok toolbar shows " Blok is enabled. It is blocking tracker requests on this site. Disable Blok for this website. "; a bunch of ads disappear
7. Open a PBM window
8. Go to tulsaworld.com
  * Blok toolbar shows " Blok is enabled. It is blocking tracker requests on this site. Disable Blok for this website. ";
9. Click "Disable Blok on this site"
  * **The first (non-PBM) window refreshes!!**

**Comment by groovecoder** [comment]
@rbillings - what version of Blok does your about:addons show?

**Comment by groovecoder** [comment]
FWIW, I sent https://github.com/mozilla/blok/pull/76 to fix the issue I found. Your issue may be related or caused by the same thing, so it may be worth trying this again after I merge that PR.

**Comment by rbillings** [comment]
extensions.bootstrappedAddons version = 2.0.17
I'll re-check after the PR is merged

**Comment by groovecoder** [comment]
I merged https://github.com/mozilla/blok/pull/76 into master, and this seems to be fixed for me with version = 0.1.8. The issue wasn't PBM-specific; *any* new/2nd window failed to enable/disable Blok because I wasn't setting the active tab ID when window focus changed.

**Comment by rbillings** [comment]
@groovecoder how do I get the updated .xpi file for testing?

**Comment by groovecoder** [comment]
Uplifting from IRC ...
```
rbillings: grab the latest .xpi from https://github.com/mozilla/blok/tree/master/web-ext-artifacts
10:24 AM <groovecoder> rbillings: working on a process this week that will create a -latest.xpi file, but it’s not done yet
10:30 AM <rbillings> groovecoder: thanks- the link in the README goes directly to the old version, so this is very helpful
10:31 AM <groovecoder> rbillings: yeah, sorry about that. pdehaan has a fix for that in https://github.com/mozilla/blok/pull/68/files
```

**Comment by rbillings** [comment]
Tested with the new .xpi file and everything looks good.
