### ISSUE TITLE
Blok bar is rendered over the website content

### ISSUE THREAD

**Issue by emilpasca** [mozilla/blok#78]
![block_bar_issue](https://cloud.githubusercontent.com/assets/20083658/17296333/5c6e6432-5809-11e6-8305-67a1a2f41da3.jpg)
[Affected versions]:
	- Firefox 48 and up.
	- Blok 0.1.7

[Affected Platforms]:
    - All Linux.

[Prerequisites]:
    - Latest Blok add-on (0.1.7) is installed.

[Steps to reproduce]:
	1. Navigate to cnn.com website.
	2. Observe how the Blok bar is displayed in relation with the website content.

[Expected result]:
The Blok bar is displayed above the website content whithout affecting the view of page elements.

[Actual result]:
Blok bar is rendered over the website content, making content unreadable or unaccessible.

[Notes]:
	- Attached a screenshot of the issue.

**Comment by groovecoder** [comment]
Thanks for the bug report! Looks like this happens on certain websites. We should use this issue to survey a number of most popular websites (top 100? 500?) to try to fix as many as possible at once.

Do you mind trying to survey some more most-popular websites and add a list of broken sites back here?

**Comment by emilpasca** [comment]
@groovecoder Sure, I will check some of the most-popular websites and come back with the results.

**Comment by pdehaan** [comment]
Another example is a mid-air :boom: with the NoMore404s add-on, which also tries to add a toolbar:

<img width="1439" alt="screenshot_8_2_16__12_58_pm" src="https://cloud.githubusercontent.com/assets/557895/17343104/f7192808-58b0-11e6-9c5f-3f6a4415a361.png">

**Comment by pdehaan** [comment]
Also breaking the pinned header in Test Pilot:

![firefox_test_pilot_-_blok](https://cloud.githubusercontent.com/assets/557895/17375312/3cb49532-5965-11e6-9573-77f2cf41dd3d.png)
**Figure 1:** Before scrolling.

---

![firefox_test_pilot_-_blok](https://cloud.githubusercontent.com/assets/557895/17375329/4d2a17fc-5965-11e6-89d9-3a21b41b7054.png)
**Figure 2:** After scrolling with pinned header. Note how the Blok header blocks the green bar.

---

![firefox_test_pilot_-_blok](https://cloud.githubusercontent.com/assets/557895/17375380/8aa82b82-5965-11e6-994b-9a3df2f1b7e1.png)
**Figure 3:** With Blok disabled, note the green bar at top which was previously obscured by Blok.

**Comment by groovecoder** [comment]
I tried fixing this by changing any elements on the page that have `{ position: fixed; top: 0}` to `{position:fixed; top: 26px}` to move them under the notification toolbar.

But I can't do that because the styles are loaded and applied from other origins. Firefox (rightly) says "Operation is insecure."

So, I don't think we can "fix" this ... the best we can do is probably to restore the close button to the toolbar so when it's rendered over website content, the user can at least close it.
