### ISSUE TITLE
Improve visibility of shield icon

### ISSUE THREAD

**Issue by ashgrigas** [mozilla/blok#8]
Moving the shield to the left side of the identity block will make it more visible as someone scans a site url or checks its security states (lock icon). 

Recommend using the existing shield icon but making it in color so that it stands out more than the existing gray version. 

For placement, I could imagine putting it behind the carrot like we do for some notifications like passwords/plug-ins - it would give it some separation from the main icon set since this is a plug-in.

**Comment by groovecoder** [comment]
Moving the icon to the left of the identity block requires re-writing the add-on as a XUL-style add-on, which seems like a high cost for ___? value.

We have a few UI options with Web Extensions:
 
* Browser Action displays an icon in the browser toolbar. This is how all other ad-/tracker-blockers (AdBlock Plus, Disconnect, ublock) are implemented.
* Page Action displays an icon in the address bar. This is the current implementation.
* Content Script can inject/add/overlay content on the web page

Would a Browser Action and/or Content Script improve visibility enough?

**Comment by ashgrigas** [comment]
Hadn't we talked about doing something like or notification bar for people
to submit feedback? That would bring more visibility than the icon itself
on the page in a more direct way. Can we 'inject' something like that at
the top or bottom of the page? A browser toolbar icon I think may be hard
to standout compared to other add-ons the user may have installed so
probably prefer current treatment to that. Can we animate the shield using
a number count of trackers?

A

On Tue, Jun 28, 2016 at 4:13 PM, luke crouch <notifications@github.com>
wrote:

> Moving the icon to the left of the identity block requires re-writing the
> add-on as a XUL-style add-on, which seems like a high cost for ___? value.
>
> We have a few UI options with Web Extensions:
>
>    - Browser Action displays an icon in the browser toolbar. This is how
>    all other ad-/tracker-blockers (AdBlock Plus, Disconnect, ublock) are
>    implemented.
>    - Page Action displays an icon in the address bar. This is the current
>    implementation.
>    - Content Script can inject/add/overlay content on the web page
>
> Would a Browser Action and/or Content Script improve visibility enough?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/groovecoder/blok/issues/8#issuecomment-229168486>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AI_-mOuRBGGsVeFrckwnTwCpFVyq2pcPks5qQYBrgaJpZM4JAM2q>
> .
>



-- 
Aislinn Dewey Grigas
User Experience Design Consultant
www.aislinndewey.com
978.930.3729
------------------------------
<http://www.linkedin.com/in/aislinn>   <http://www.twitter.com/ashdewey>
<http://www.facebook.com/ashdewey>

**Comment by groovecoder** [comment]
Yeah, we can add an in-page notification bar with a content script. I agree it will pull more attention.

**Comment by groovecoder** [comment]
Fixed via https://github.com/mozilla/blok/pull/13
