### ISSUE TITLE
Add generic "close" button to toolbar

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#81]
Just spotted this, and thought adding a "close" button may be nice, if user's just want to dismiss the Block header completely without doing anything.

<img width="1065" alt="firefox_test_pilot_-_experiments" src="https://cloud.githubusercontent.com/assets/557895/17301053/f8a8fbd6-57c9-11e6-922c-268aa3a628a7.png">

**Comment by pdehaan** [comment]
Oddly it looks like the screenshot in the README has a close button (despite the Block toolbar being at the bottom of the page) https://github.com/mozilla/blok#run-it

![](https://github.com/mozilla/blok/blob/master/docs/screenshot.png?raw=true)

**Comment by groovecoder** [comment]
Yeah, that screenshot is old. :(

**Comment by pdehaan** [comment]
Any idea why we had it and removed it?
