### ISSUE TITLE
Banner text is truncated at smaller page widths

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#83]
<img width="1080" alt="firefox_nightly_first_run_page" src="https://cloud.githubusercontent.com/assets/557895/17309186/779b5286-57f2-11e6-8085-3ec6a7f53662.png">
**Figure 1:** Blok is enabled. It is blocking requests for this site. [Disable Blok for this website.]()

---

<img width="976" alt="firefox_nightly_first_run_page" src="https://cloud.githubusercontent.com/assets/557895/17309288/f78843f0-57f2-11e6-98ed-8844b7377834.png">
**Figure 2:** Blok is enabled. It is blocking requests for this site. [Disable Blok for this]()

---

<img width="703" alt="firefox_nightly_first_run_page" src="https://cloud.githubusercontent.com/assets/557895/17309340/44770cbe-57f3-11e6-86c5-2e6113f26c6f.png">
**Figure 3:** Blok is enabled. It is blocking requests for this

---

... You get the idea.

**Comment by groovecoder** [comment]
Closing this since we're changing the toolbar into a page action. https://github.com/mozilla/blok/issues/107
