### ISSUE TITLE
Auto close toolbar after giving feedback?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#84]
<img width="718" alt="pinterest_ _the_world s_catalog_of_ideas" src="https://cloud.githubusercontent.com/assets/557895/17343970/36594f44-58b5-11e6-9446-f72241cbea44.png">

I clicked the "This page works well" but the toolbar still stays visible and obscures my page. Not sure if we want to auto-close the toolbar after 3-4 seconds after the user gives feedback.

Ref: #78 
Ref: #81

**Comment by groovecoder** [comment]
Closing since we're changing the toolbar into a page action.
