### ISSUE TITLE
Cannot submit feedback form when window is too short

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blok#85]
Click the **Report a problem** button in the Blok toolbar.

<img width="718" alt="pinterest_ _the_world s_catalog_of_ideas" src="https://cloud.githubusercontent.com/assets/557895/17344261/51ba5c00-58b6-11e6-9801-b043a2a4ca4e.png">

I can't seem to scroll down the feedback form to the **Submit** button. Scrolling seems to scroll the page in the background, not the feedback form.

**Workaround:** Resize the window higher to see the bottom of the form.

<img width="718" alt="pinterest_ _the_world s_catalog_of_ideas" src="https://cloud.githubusercontent.com/assets/557895/17344386/b4794900-58b6-11e6-968f-0b3f4e9be21d.png">

**Comment by groovecoder** [comment]
Closing this since we're changing the feedback modal into a page action pop-up. https://github.com/mozilla/blok/issues/107
