### ISSUE TITLE
Improve copy in notification bar

### ISSUE THREAD

**Issue by ashgrigas** [mozilla/blok#9]
Suggest shortening copy to say:
'Disable blocking for this site' (remove tab)

Also may want to reference the add-on name in the copy at the top, like 'XXX Add-on' blocked 15 requests that may be tracking your browsing."

We can have our copywriter weigh in as well...

**Comment by groovecoder** [comment]
Good call ... I removed the "in this tab" copy in https://github.com/groovecoder/blok/pull/10 at the same time I made it possible to disable blocking for sites regardless of tabs.

So "Blok add-on blocked 15 requests to sites that may be tracking you." ?

**Comment by ashgrigas** [comment]
Can we say 'Blok add-on blocked 15 sites that may be tracking your browsing
behavior".?

On Tue, Jun 28, 2016 at 4:16 PM, luke crouch <notifications@github.com>
wrote:

> Good call ... I removed the "in this tab" copy in #10
> <https://github.com/groovecoder/blok/pull/10> at the same time I made it
> possible to disable blocking for sites regardless of tabs.
>
> So "Blok add-on blocked 15 requests to sites that may be tracking you." ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/groovecoder/blok/issues/9#issuecomment-229169422>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AI_-mGYqiQ67DnbDZPCG9lTHvHJEQEVyks5qQYEzgaJpZM4JANBh>
> .
>



-- 
Aislinn Dewey Grigas
User Experience Design Consultant
www.aislinndewey.com
978.930.3729
------------------------------
<http://www.linkedin.com/in/aislinn>   <http://www.twitter.com/ashdewey>
<http://www.facebook.com/ashdewey>

**Comment by groovecoder** [comment]
@ashgrigas - need your fresh input on this. In the latest notification bar UI in master, I followed the UX of the pop-up blocker, so the copy now says:

> Blok prevented this site from requesting NN trackers.

and

> Disable Blok

PBM says:

> Private windows now block parts of the page that may track your browsing activity.

> Turn Tracking Protection Off

on the PBM new window, and:

> Firefox is blocking some parts of the page that could track your browsing activity

> Some page areas may be missing, because they could allow third parties to track you across different websites.

> Disable protection for this session

in the (IMO excellent) on-boarding tour.

But ... 

> The language and means we are using to communicate both PBM and Tracking Protection is sometimes vague or overly technical
>
> Many participants do not have an accurate mental model of how private browsing or Tracking Protection work. In the absence of a clear understanding, they carry many misconceptions.
> 
> Based on post-diary study interviews, the on-boarding tour did not increase most participants’ understanding of how PBM or Tracking Protection work.

So: **should** we use the same copy as the existing PBM TP experience? Could we do some copy comparison between PBM TP, ad-block plus, ghostery, uBlock Origin? To get really fancy, could we measure how accurately users understand pop-up blocker and use that as a baseline for a tracker blocker? Or should we just go with whatever we think is the best for this new implementation?

**Comment by ashgrigas** [comment]
Hey Luke,
I think the question we should ask is how are test pilot users potentially
different (more advanced?) than typical users of private browsing mode and
the general users we tested with in the diary study? My guess is they are
more aware of what trackers are and the benefit of tracking protection
compared to the average PBM user. I think its ok to adjust the copy for the
add-on as needed since a lot of our original copy was watered down for
legal/policy reasons and maybe we can overcome that in an add-on through
test pilot versus in product. Also the copy that was tested in the diary
study may not have been the version of TP in nightly we tested with users.
We went through several versions so I wouldn't base the feedback solely on
that one study.

Can you send me the screencaps of the current design you have and i can
annotate it with suggestions for copy and styling?

A

On Tue, Jul 5, 2016 at 10:10 AM, luke crouch <notifications@github.com>
wrote:

> @ashgrigas <https://github.com/ashgrigas> - need your fresh input on
> this. In the latest notification bar UI in master, I followed the UX of the
> pop-up blocker, so the copy now says:
>
> Blok prevented this site from requesting NN trackers.
>
> and
>
> Disable Blok
>
> PBM says:
>
> Private windows now block parts of the page that may track your browsing
> activity.
>
> Turn Tracking Protection Off
>
> on the PBM new window, and:
>
> Firefox is blocking some parts of the page that could track your browsing
> activity
>
> Some page areas may be missing, because they could allow third parties to
> track you across different websites.
>
> Disable protection for this session
>
> in the (IMO excellent) on-boarding tour.
>
> But ...
>
> The language and means we are using to communicate both PBM and Tracking
> Protection is sometimes vague or overly technical
>
> Many participants do not have an accurate mental model of how private
> browsing or Tracking Protection work. In the absence of a clear
> understanding, they carry many misconceptions.
>
> Based on post-diary study interviews, the on-boarding tour did not
> increase most participants’ understanding of how PBM or Tracking Protection
> work.
>
> So: *should* we use the same copy as the existing PBM TP experience?
> Could we do some copy comparison between PBM TP, ad-block plus, ghostery,
> uBlock Origin? To get really fancy, could we measure how accurately users
> understand pop-up blocker and use that as a baseline for a tracker blocker?
> Or should we just go with whatever we think is the best for this new
> implementation?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/blok/issues/9#issuecomment-230489096>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AI_-mA4XuoWrqEro6P8SdF8xi5jgXqDKks5qSmXSgaJpZM4JANBh>
> .
>



-- 
Aislinn Dewey Grigas
User Experience Design Consultant
www.aislinndewey.com
978.930.3729
------------------------------
<http://www.linkedin.com/in/aislinn>   <http://www.twitter.com/ashdewey>
<http://www.facebook.com/ashdewey>

**Comment by groovecoder** [comment]
@ashgrigas https://raw.githubusercontent.com/groovecoder/blok/master/img/screenshot.png now has the latest screen-grab with the bottom-hanging notification bar. Is that enough for copy suggestions/edits?

**Comment by ashgrigas** [comment]
yes - im waiting on copy which i should have end of day weds for you. we
can also review in our meeting today the design sketches i have.

On Tue, Jul 12, 2016 at 1:52 PM, luke crouch <notifications@github.com>
wrote:

> @ashgrigas <https://github.com/ashgrigas>
> https://raw.githubusercontent.com/groovecoder/blok/master/img/screenshot.png
> now has the latest screen-grab with the bottom-hanging notification bar. Is
> that enough for copy suggestions/edits?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/blok/issues/9#issuecomment-232125481>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AI_-mLXovP1ddrM_avHtoOd2woMRTCHVks5qU9RXgaJpZM4JANBh>
> .
>



-- 
Aislinn Dewey Grigas
User Experience Design Consultant
www.aislinndewey.com
978.930.3729
------------------------------
<http://www.linkedin.com/in/aislinn>   <http://www.twitter.com/ashdewey>
<http://www.facebook.com/ashdewey>

**Comment by groovecoder** [comment]
Closing this issue now that we have https://github.com/mozilla/blok/issues/22
